### ISSUE TITLE
please rebuild to newer LethalLib so it works in modded moons!

### ISSUE THREAD

**Issue by broilerosu** [cpinta/PintoBoy-LethalCompanyMod#2]
![image](https://github.com/cpinta/PintoBoy-LethalCompanyMod/assets/47702237/a3e07c82-5720-49e9-81f3-cd13ccfa5335)

please fix can only use it in vanilla levels

**Comment by broilerosu** [comment]
needs 
![image](https://github.com/cpinta/PintoBoy-LethalCompanyMod/assets/47702237/62b22094-43ef-44e7-9591-2b148dd7c59b)

**Comment by cpinta** [comment]
Sorry for the inconvenience, just updated it with this
